import type { Metadata } from 'next';
import TopBar from './components/TopBar';
import BottomBar from './components/BottomBar';
import { Oswald, IBM_Plex_Sans } from 'next/font/google';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const oswald = Oswald({
  subsets: ['latin'],
});
const IBMPlexSans = IBM_Plex_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = [
    { name: 'Home', href: '#' },
    { name: 'About', href: '#' },
    { name: 'Services', href: '#' },
    { name: 'Portfolio', href: '#' },
    { name: 'Insights', href: '#' },
    { name: 'Contact', href: '#' },
  ];

  return (
    <html lang='en' className={`${oswald.className} ${IBMPlexSans.className}`}>
      <body>
        <TopBar />
        {children}
        <BottomBar pages={pages} />
      </body>
    </html>
  );
}
